# Generated by Django 4.1.2 on 2023-03-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_name', models.CharField(max_length=100)),
                ('star_dob', models.IntegerField()),
                ('star_place', models.CharField(max_length=100)),
                ('Best_known_role', models.CharField(max_length=200, null=True)),
                ('star_awards_nominated', models.IntegerField()),
                ('star_awards_won', models.IntegerField()),
                ('Imdb_actorURL', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_name', models.CharField(max_length=100)),
                ('dr_dob', models.IntegerField()),
                ('dr_place', models.CharField(max_length=100)),
                ('dr_awards_nominated', models.IntegerField()),
                ('dr_awards_won', models.IntegerField()),
                ('Imdb_directorURL', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Genre_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Movie_name', models.CharField(max_length=200)),
                ('year', models.IntegerField(null=True)),
                ('runtime', models.CharField(max_length=10, null=True)),
                ('Gross_collection', models.IntegerField(null=True)),
                ('Produced_by', models.CharField(max_length=100)),
                ('Imdb_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('Imdb_url', models.CharField(max_length=200)),
                ('Cast', models.ManyToManyField(to='movies.actor')),
                ('Directed_by', models.ManyToManyField(to='movies.director')),
                ('Genre', models.ManyToManyField(to='movies.genre')),
            ],
        ),
    ]
