# Generated by Django 4.1.2 on 2023-04-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('runtime', models.CharField(max_length=10, null=True)),
                ('cast', models.CharField(blank=True, max_length=100, null=True)),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('director', models.CharField(blank=True, max_length=100, null=True)),
                ('producer', models.CharField(blank=True, max_length=100, null=True)),
                ('imdb_rating', models.CharField(blank=True, max_length=10, null=True)),
                ('imdb_url', models.CharField(max_length=200)),
                ('thumbnail_url', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
