# Generated by Django 4.1.2 on 2023-04-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='star_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='director',
            old_name='dr_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='Genre_type',
            new_name='genre_type',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='Cast',
            new_name='cast',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='Directed_by',
            new_name='director',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='Genre',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='Imdb_url',
            new_name='imdb_url',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='Movie_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='Best_known_role',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='Imdb_actorURL',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='star_awards_nominated',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='star_awards_won',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='star_dob',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='star_place',
        ),
        migrations.RemoveField(
            model_name='director',
            name='Imdb_directorURL',
        ),
        migrations.RemoveField(
            model_name='director',
            name='dr_awards_nominated',
        ),
        migrations.RemoveField(
            model_name='director',
            name='dr_awards_won',
        ),
        migrations.RemoveField(
            model_name='director',
            name='dr_dob',
        ),
        migrations.RemoveField(
            model_name='director',
            name='dr_place',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='Gross_collection',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='Imdb_rating',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='Produced_by',
        ),
        migrations.AddField(
            model_name='movies',
            name='producer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='imdb_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
