# Generated by Django 4.1.2 on 2023-04-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb_url',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
